import { StyleSheet } from 'react-native';
import commonStyles from '../../common/styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 10,
    backgroundColor: commonStyles.colors.color_1,
  },
  scrollView: {
    padding: 10,
  },
  header: {
    fontSize: 20,
    alignSelf: 'center',
    marginBottom: 10,
  },
  postTextInput: {
    backgroundColor: commonStyles.colors.color_6,
    borderRadius: 5,
    padding: 5,
    textAlign: 'left',
    textAlignVertical: 'top',
  },
  textInput: {
    backgroundColor: commonStyles.colors.color_6,
    borderRadius: 5,
    marginTop: 0,
  },
  currencyTextInput: {
    backgroundColor: commonStyles.colors.color_6,
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    marginTop: 0,
    flex: 2,
    textAlign: 'right',
    height: 48,
  },

  submitButton: {
    height: 48,
    backgroundColor: commonStyles.colors.ok_button_color,
    marginTop: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    marginRight: 10,
  },
  disabledButton: {
    height: 48,
    backgroundColor: commonStyles.colors.gray,
    marginTop: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    marginRight: 10,
  },
  submitButtonText: {
    color: commonStyles.colors.label_color,
  },
  imagePanel: {
    marginTop: 10,
    marginBottom: 10,
    // borderWidth: 1,
    // borderColor: commonStyles.colors.gray,
    borderRadius: 10,
    height: 120,
    padding: 5,
    alignItems: 'center',
    backgroundColor: commonStyles.colors.light_gray,
    justifyContent: 'center',
  },
  imagePanelText: {
    fontWeight: 'bold',
  },
  timePanel: {
    flexDirection: 'row',
  },
  startTimePanel: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    minHeight: 48,
    padding: 5,
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    marginRight: 1,
    backgroundColor: commonStyles.colors.color_4,
  },
  endTimePanel: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    minHeight: 48,
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    padding: 5,
    marginLeft: 1,
    backgroundColor: commonStyles.colors.color_6,
  },
  locationPanel: {
    flexDirection: 'row',
    flex: 1,
    width: '100%',
    backgroundColor: commonStyles.colors.color_4,
    borderRadius: 5,
  },
  paymentPanel: {},
  icon: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    color: commonStyles.colors.label_color,
  },
  iconButton: {
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: commonStyles.colors.label_color,
    marginTop: 0,
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
  },
  picker: {
    width: 100,
    backgroundColor: '#FFF',
    height: 48,

  },
  currencyPanel: {
    flexDirection: 'row',
  },
  timeHeader: {
    fontWeight: 'bold',
    alignItems: 'center',
    alignSelf: 'center',
    color: commonStyles.colors.label_color,
  },
  timeLabel: {
    marginTop: 5,
    alignItems: 'center',
    alignSelf: 'center',
    color: commonStyles.colors.label_color,
  },
  dateLabel: {
    marginTop: 5,
  },
  tagPanel: {
    marginTop: 5,
    marginBottom: 5,
  },
  tags: {
    flex: 1,
    height: 40,
    backgroundColor: commonStyles.colors.formBackground,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 5,
  },
  tag: {
    marginLeft: 5,
    marginRight: 5,
    backgroundColor: '#EEE',
    borderRadius: 5,
    padding: 5,
  },
  tagView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagButton: {
    color: '#111',
    marginLeft: 5,
  },
  tagLabel: {

  },
  mapView: {
    height: 80,
    width: '95%',
    flex: 1,
    margin: 5,
    borderRadius: 5,
  },
  emptyMapView: {
    height: 48,
    // backgroundColor: commonStyles.colors.label_color,
    padding: 5,
    flex: 2,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyMapViewLabel: {
    color: commonStyles.colors.label_color,
    fontWeight: 'bold',
    padding: 5,
  },
});

export default styles;
