import { StyleSheet } from 'react-native';
import commonStyles from '../../common/styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: commonStyles.colors.color_1,
  },
  header: {
    fontSize: 20,
    alignSelf: 'center',
    marginBottom: 10,
  },
  postTextInput: {
    backgroundColor: `${commonStyles.colors.color_6}FF`,
    borderRadius: 5,
    padding: 5,
    textAlignVertical: 'top',
  },
  textInput: {
    backgroundColor: `${commonStyles.colors.color_6}FF`,
    borderRadius: 5,
    marginTop: 0,
    borderWidth: 1,
    borderColor: commonStyles.colors.color_4,
  },
  currencyTextInput: {
    backgroundColor: `${commonStyles.colors.color_6}FF`,
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    marginTop: 0,
    flex: 2,
    // borderWidth: 1,
    // borderColor: commonStyles.colors.color_6,
    textAlign: 'right',
    height: 48,
  },
  locationTextInput: {
    backgroundColor: `${commonStyles.colors.color_6}FF`,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    marginTop: 0,
    flex: 2,
    borderWidth: 1,
    borderColor: commonStyles.colors.color_6,
    height: 48,

  },
  submitButton: {
    height: 48,
    backgroundColor: commonStyles.colors.ok_button_color,
    marginTop: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: {
    color: commonStyles.colors.label_color,
  },
  imagePanel: {
    marginTop: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: commonStyles.colors.color_4,
    borderRadius: 10,
    minHeight: 80,
    alignItems: 'center',
    backgroundColor: commonStyles.colors.light_gray,
    justifyContent: 'center',
  },
  imagePanelText: {
    fontWeight: 'bold',
  },
  timePanel: {
    flexDirection: 'row',
  },
  startTimePanel: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    borderWidth: 1,
    minHeight: 48,
    borderColor: commonStyles.colors.color_4,
    padding: 5,
    borderBottomLeftRadius: 5,
    borderTopLeftRadius: 5,
    marginRight: 1,
    backgroundColor: commonStyles.colors.color_4,
  },
  endTimePanel: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    minHeight: 48,
    borderWidth: 1,
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    borderColor: commonStyles.colors.color_6,
    padding: 5,
    marginLeft: 1,
    backgroundColor: commonStyles.colors.color_6,
  },
  locationPanel: {
    flexDirection: 'row',
    flex: 1,
    width: '100%',
    backgroundColor: commonStyles.colors.color_4,
    borderRadius: 5,
  },
  paymentPanel: {},
  icon: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    color: commonStyles.colors.label_color,
  },
  iconButton: {
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: commonStyles.colors.label_color,
    marginTop: 0,
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
  },
  picker: {
    flex: 1,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    marginTop: 0,
    marginLeft: 2,
    borderColor: commonStyles.colors.color_1,
    backgroundColor: commonStyles.colors.color_6,
  },
  currencyPanel: {
    flexDirection: 'row',
  },
  timeHeader: {
    // fontSize: 16,
    fontWeight: 'bold',
    alignItems: 'center',
    alignSelf: 'center',
    color: commonStyles.colors.label_color,
  },
  timeLabel: {
    marginTop: 5,
    alignItems: 'center',
    alignSelf: 'center',
    color: commonStyles.colors.label_color,
  },
  dateLabel: {
    marginTop: 5,
  },
  mapView: {
    height: 80,
    // width: '100%',
    flex: 1,
    margin: 5,
    borderRadius: 5,
  },
  emptyMapView: {
    height: 48,
    // backgroundColor: commonStyles.colors.label_color,
    padding: 5,
    flex: 2,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyMapViewLabel: {
    color: commonStyles.colors.label_color,
    fontWeight: 'bold',
  },
});

export default styles;
