import helper from '../utils/type_helper';

const NAME = 'requests';

export const LOAD_REQUESTS = helper(NAME, 'LOAD_REQUESTS');
export const REQUESTS_LOADED = helper(NAME, 'REQUESTS_LOADED');
export const LOAD_REQUESTS_FAILED = helper(NAME, 'LOAD_REQUESTS_FAILED');

export const GET_MY_REQUESTS = helper(NAME, 'GET_MY_REQUESTS');
export const GETTING_MY_REQUESTS = helper(NAME, 'GETTING_MY_REQUESTS');
export const MY_REQUESTS_RECEIVED = helper(NAME, 'MY_REQUESTS_RECEIVED');
export const GET_MY_REQUESTS_FAILED = helper(NAME, 'GET_MY_REQUESTS_FAILED');

export const CREATE_REQUEST = helper(NAME, 'CREATE_REQUEST');
export const CREATING_REQUEST = helper(NAME, 'CREATING_REQUEST');
export const CREATE_REQUEST_FAILED = helper(NAME, 'CREATE_REQUEST_FAILED');
export const REQUEST_CREATED = helper(NAME, 'REQUEST_CREATED');

export const ACTIVATE_REQUEST = helper(NAME, 'ACTIVATE_REQUEST');
export const ACTIVATING_REQUEST = helper(NAME, 'ACTIVATING_REQUEST');
export const ACTIVATING_REQUEST_FAILED = helper(NAME, 'ACTIVATING_REQUEST_FAILED');
export const REQUEST_ACTIVATED = helper(NAME, 'REQUEST_ACTIVATED');

export const UPLOAD_IMAGE = helper(NAME, 'UPLOAD_IMAGE');
export const UPLOADING_IMAGE = helper(NAME, 'UPLOADING_IMAGE');
export const UPLOADING_IMAGE_SUCCESS = helper(NAME, 'UPLOADING_IMAGE_SUCCESS');
export const UPLOADING_IMAGE_FAILED = helper(NAME, 'UPLOADING_IMAGE_FAILED');

export const LOAD_REQUEST = helper(NAME, 'LOAD_REQUEST');
export const REQUEST_LOADED = helper(NAME, 'REQUEST_LOADED');
export const LOAD_REQUEST_FAILED = helper(NAME, 'LOAD_REQUEST_FAILED');

export const SHOW_REQUEST = helper(NAME, 'SHOW_REQUEST');
export const SHOW_REQUEST_FAILED = helper(NAME, 'SHOW_REQUEST_FAILED');
export const REQUEST_SHOWED = helper(NAME, 'REQUEST_SHOWED');

export const EDIT_REQUEST = helper(NAME, 'EDIT_REQUEST');
export const REQUEST_EDITED = helper(NAME, 'REQUEST_EDITED');
export const EDIT_REQUEST_FAILED = helper(NAME, 'EDIT_REQUEST_FAILED');

export const DELETE_REQUEST = helper(NAME, 'DELETE_REQUEST');
export const DELETE_REQUEST_FAILED = helper(NAME, 'DELETE_REQUEST_FAILED');
export const REQUEST_DELETED = helper(NAME, 'REQUEST_DELETED');

export const PROMOTE_REQUEST = helper(NAME, 'PROMOTE_REQUEST');
export const REQUEST_PROMOTED = helper(NAME, 'REQUEST_PROMOTED');
export const PROMOTE_REQUEST_FAILED = helper(NAME, 'PROMOTE_REQUEST_FAILED');

export const CHECK_PROMOTED = helper(NAME, 'CHECK_PROMOTED');
export const PROMOTED_CHECKED = helper(NAME, 'PROMOTED_CHECKED');
export const CHECK_PROMOTED_FAILED = helper(NAME, 'CHECK_PROMOTED_FAILED');

export const SHOW_REQUESTS_FOR_SERVICE = helper(NAME, 'SHOW_REQUESTS_FOR_SERVICE');
export const LOAD_REQUESTS_FOR_SERVICE = helper(NAME, 'LOAD_REQUESTS_FOR_SERVICE');
export const REQUESTS_FOR_SERVICE_LOADED = helper(NAME, 'REQUESTS_FOR_SERVICE_LOADED');
export const LOAD_REQUESTS_FOR_SERVICE_FAILED = helper(NAME, 'LOAD_REQUESTS_FOR_SERVICE_FAILED');
