import { StyleSheet } from 'react-native';
import commonStyles from '../common/styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexGrow: 1,
    backgroundColor: commonStyles.colors.color_4,
  },
  slide: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: `${commonStyles.colors.color_1}FF`,
    padding: 50,
    paddingBottom: 80,
    paddingTop: 80,
  },
  swiper: {
    flex: 1,
  },
  bottomPanel: {},
  textPanel: {
    backgroundColor: '#3363',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  mainText: {
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '600',
    padding: 10,
    color: commonStyles.colors.color_6,
  },
  invitePanelText: {
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '600',
    padding: 10,
    color: commonStyles.colors.color_6,
    backgroundColor: '#3363',
    borderRadius: 10,
    marginBottom: 10,
  },
  subText: {
    textAlign: 'center',
    fontSize: 16,
    color: commonStyles.colors.color_6,
  },
  inviteButton: {
    backgroundColor: commonStyles.colors.color_4,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 5,
  },
  inviteText: {
    color: commonStyles.colors.color_6,
    textAlign: 'center',
    fontWeight: 'bold',
    backgroundColor: commonStyles.colors.color_4,
    padding: 10,
    textAlignVertical: 'center',
    // borderRadius: 5,
  },
  iconImage: {
    color: commonStyles.colors.color_6,
  },
  signinButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: commonStyles.colors.color_2,
    padding: 10,
    height: 48,
    borderRadius: 5,
  },
  signinButtonText: {
    color: commonStyles.colors.color_6,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 16,
    fontWeight: 'bold',
  },
  appNamePanel: {
    backgroundColor: '#3363',
    padding: 10,
    marginBottom: 40,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appIcon: {
    width: 60,
    height: 60,
  },
  appName: {
    color: commonStyles.colors.color_6,
    fontSize: 28,
    fontWeight: 'bold',
    marginLeft: 20,
  },
  sliderButton: {
    color: commonStyles.colors.color_6,
    fontSize: 80,
    fontWeight: 'bold',
    // backgroundColor: commonStyles.colors.darkTransparentBackground,
    // textAlign: 'center',
    // textAlignVertical: 'center',
    // alignItems: 'center',
    // justifyContent: 'center',
    // backgroundColor: '#222A',
    padding: 5,
    borderRadius: 10,
  },
  dot: {
    backgroundColor: 'rgba(255,255,255,.3)',
    width: 13,
    height: 13,
    borderRadius: 7,
    marginLeft: 7,
    marginRight: 7,
  },
  activeDot: {
    backgroundColor: '#fff',
    width: 13,
    height: 13,
    borderRadius: 7,
    marginLeft: 7,
    marginRight: 7,
  },
});

export default styles;
