import helper from '../utils/type_helper';

const NAME = 'responses';

export const CREATE_RESPONSE = helper(NAME, 'CREATE_RESPONSE');
export const CREATING_RESPONSE = helper(NAME, 'CREATING_RESPONSE');
export const CREATE_RESPONSE_FAILED = helper(NAME, 'CREATE_RESPONSE_FAILED');
export const RESPONSE_CREATED = helper(NAME, 'RESPONSE_CREATED');

export const ACTIVATING_RESPONSE = helper(NAME, 'ACTIVATING_RESPONSE');

export const LOAD_RESPONSES_FOR_REQUEST = helper(NAME, 'LOAD_RESPONSES_FOR_REQUEST');
export const LOADING_RESPONSES_FOR_REQUEST = helper(NAME, 'LOADING_RESPONSES_FOR_REQUEST');
export const RESPONSES_FOR_REQUEST_LOADED = helper(NAME, 'RESPONSES_FOR_REQUEST_LOADED');
export const LOAD_RESPONSES_FOR_REQUEST_FAILED = helper(NAME, 'LOAD_RESPONSES_FOR_REQUEST_FAILED');

export const ACCEPT_RESPONSE = helper(NAME, 'ACCEPT_RESPONSE');
export const ACCEPTING_RESPONSE = helper(NAME, 'ACCEPTING_RESPONSE');
export const RESPONSE_ACCEPTED = helper(NAME, 'RESPONSE_ACCEPTED');
export const ACCEPTING_RESPONSE_FAILED = helper(NAME, 'ACCEPTING_RESPONSE_FAILED');


export const EDIT_RESPONSE = helper(NAME, 'EDIT_RESPONSE');
export const EDITING_RESPONSE = helper(NAME, 'EDITING_RESPONSE');
export const RESPONSE_EDITED = helper(NAME, 'RESPONSE_EDITED');
export const EDIT_RESPONSE_FAILED = helper(NAME, 'EDIT_RESPONSE_FAILED');

export const DELETE_RESPONSE = helper(NAME, 'DELETE_RESPONSE');
export const DELETE_RESPONSE_FAILED = helper(NAME, 'DELETE_RESPONSE_FAILED');
export const RESPONSE_DELETED = helper(NAME, 'RESPONSE_DELETED');

export const SHOW_RESPONSE = helper(NAME, 'SHOW_RESPONSE');
export const LOAD_RESPONSE = helper(NAME, 'LOAD_RESPONSE');
export const RESPONSE_LOADED = helper(NAME, 'RESPONSE_LOADED');
export const LOAD_RESPONSE_FAILED = helper(NAME, 'LOAD_RESPONSE_FAILED');
